# Generated by Django 4.2.14 on 2026-08-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantMemoryScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_key", models.CharField(db_index=True, max_length=180, unique=True)),
                ("slots", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True, default="")),
                ("summary_through_sequence", models.PositiveBigIntegerField(default=0)),
                ("summary_revision", models.PositiveIntegerField(default=0)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_memory_scopes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_assistant_memory_scope",
            },
        ),
        migrations.CreateModel(
            name="AssistantMemoryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveBigIntegerField(),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("human", "Human"), ("ai", "Assistant")],
                        max_length=12,
                    ),
                ),
                ("content", models.TextField()),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "legacy_message_id",
                    models.PositiveBigIntegerField(blank=True, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_assistant.assistantmemoryscope",
                    ),
                ),
            ],
            options={
                "db_table": "ai_assistant_memory_message",
            },
        ),
        migrations.AddIndex(
            model_name="assistantmemoryscope",
            index=models.Index(fields=["owner", "updated_at"], name="ai_assistan_owner_i_bc6671_idx"),
        ),
        migrations.AddConstraint(
            model_name="assistantmemorymessage",
            constraint=models.UniqueConstraint(
                fields=("scope", "sequence"),
                name="ai_memory_scope_sequence_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="assistantmemorymessage",
            index=models.Index(fields=["scope", "sequence"], name="ai_assistan_scope_i_fe982c_idx"),
        ),
        migrations.AddIndex(
            model_name="assistantmemorymessage",
            index=models.Index(fields=["scope", "created_at"], name="ai_assistan_scope_i_b31a91_idx"),
        ),
    ]
